Repository scratchfoundation/scratch-l10n, pull requests merged in 2019-01, with the labels that each got.

#59 Fix placeholder checking
  scripts/tx-util.js
Labels: pr - good to merge

#60 Jan update languages
  editor/blocks/bg.json
  editor/blocks/lv.json
  editor/blocks/nn.json
  editor/blocks/sk.json
  editor/extensions/bg.json
  editor/extensions/hu.json
  editor/extensions/lv.json
  editor/extensions/nn.json
  editor/extensions/sk.json
  editor/interface/bg.json
  editor/interface/hu.json
  editor/interface/lv.json
  editor/interface/nn.json
  editor/interface/sk.json
  editor/paint-editor/bg.json
  editor/paint-editor/lv.json
  editor/paint-editor/nn.json
  editor/paint-editor/sk.json
  src/supported-locales.js
Labels: pr - good to merge

#61 Add react-intl locale data for new languages.
  src/index.js
Labels: localization

#62 added pull request template, and note on where to find react-intl info
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/index.js
Labels: pr - needs review
